### ISSUE TITLE
为什么我配置了还是一堆错误?

### ISSUE THREAD

**Issue by hms111111** [guren-cloud/weapp-one#1]

**Comment by safe-dog** [comment]
哪里错误请贴出截图或者代码，谢谢啦

**Comment by hms111111** [comment]
![1](https://user-images.githubusercontent.com/7575837/43384544-f0eff6b2-9410-11e8-973c-1d71616a6410.png)

**Comment by safe-dog** [comment]
看到贴图代码了，就是没引入vPush模块的意思，请参考：
#2 #3 
直接clone完整即可

https://github.com/safe-dog/vpush-sdk
