### ISSUE TITLE
没有vPush.js文件

### ISSUE THREAD

**Issue by yinbolove576** [guren-cloud/weapp-one#2]
libs/vpush-sdk/vPush.js 这个文件涉及隐私就没上传是吧？😂

**Comment by safe-dog** [comment]
没有啊，vPush也是开源的，直接链接到仓库了。需要使用`git clone`才会自动下载同步吧~

这个项目地址在：[https://github.com/safe-dog/vpush-sdk](https://github.com/safe-dog/vpush-sdk)
