### ISSUE TITLE
源代码的demo跟线上的小程序不一样

### ISSUE THREAD

**Issue by zmqcherish** [guren-cloud/weapp-one#4]
线上的版本是这样的，能提供线上版本的示例源码学习吗，谢谢。

![qq 20190118131839](https://user-images.githubusercontent.com/6880848/51367011-a5254800-1b23-11e9-991d-0609a46c962f.png)

**Comment by safe-dog** [comment]
你好，新版本项目现在已经开源了哈，感谢支持

**Comment by zmqcherish** [comment]
@safe-dog hello，发现您又更新了版本了呢，UI很漂亮，还是厚脸皮的求个源码学习一下。建议在小程序里加个微信的赞赏码，方便大家给予支持呢。
